#!/usr/bin/env perl

use v5.14;
say "This application isn't made to be installed into your system.";

# use inc::Module::Install 1.02;
# use Module::Install::Catalyst; # Complain loudly if you don't have
#                                # Catalyst::Devel installed or haven't said
#                                # 'make dist' to create a standalone tarball.

# name 'Mafia';
# all_from 'lib/Mafia.pm';
# perl_version '5.014';
